test_model:
    value: false
    help: "true to test the model, false to train"

# ============================
# Training Configuration
# ============================

epochs:
    value: 2
    help: "Number of epochs to train."

batch_size:
    value: 16
    help: "Batch size for training."

lr:
    value: 0.001
    help: "Learning rate."

lr_decay:
    value: 0.4
    help: "Gamma value for StepLR scheduler."

workers:
    value: 4
    help: "Number of dataloader workers."

device:
    value: "auto"
    help: "Training device: auto/cpu/cuda/mps."


freeze_backbone:
    value: true
    help: "Freeze DenseNet backbone."

freeze_vit:
    value: true
    help: "Freeze ViT encoder."

train_last_vit_layers:
    value: 0
    help: "Train only the last N transformer layers in ViT."


use_custom_proj:
    value: false
    help: "Use custom DenseNetâ†’ViT projection block."

custom_proj_layers:
    value: 512
    help: "The number of layers in the custom projection"

img_dir:
    value: "../nih_data"
    help: "Directory of image folders."

csv_path:
    value: "../nih_data/Data_Entry_2017.csv"
    help: "Path to CSV file."

save_dir:
    value: "../results"
    help: "Directory for saving checkpoints and logs."

resume:
    value: None # if you want to resume training
    help: "Checkpoint file to resume training."  # ./checkpoints/last_checkpoint.pth

verbose:
    value: true
    help: "Print detailed logs."




    